### ISSUE TITLE
Release is behind current version.

### ISSUE THREAD

**Issue by FarronF** [andysandford/sm64-livesplit-autosplitter#2]
The most recent release and as such the download in the readme do not contain the most recent version that includes the no LBLJ beginner route without BitDW red coins.

https://github.com/andysandford/sm64-livesplit-autosplitter/commit/174d114960ced56a3cb8fa66e87d5c354dbbe739

 I downloaded the changes manually but would be good for other beginners to have it easily accessible.

**Comment by andysandford** [comment]
Thanks. I have updated the link.
