### ISSUE TITLE
How does the autosplitter know which process to look into?

### ISSUE THREAD

**Issue by arty-hlr** [andysandford/sm64-livesplit-autosplitter#3]
Hi,

I was trying to modify the script for M64Py, which also uses mupen64plus as a base, but with a GUI. I thought changing this:
```
state("mupen64plus-ui-console", "JP") {
```
to that:
```
state("m64py", "JP") {
```
would do the trick as the `mupen64plus.dll` module is also loaded in this process, but unfortunately that didn't work.

Could you give some precisions about how the autosplitter chooses the process in which to look at that DLL memory? It would be great to be able to adapt the script to M64Py.

I also tried to use the `mupen64plus.exe` shipped with M64Py, but even renamed as `mupen64plus-ui-console.exe` to match that `state`, it didn't work.

**Comment by andysandford** [comment]
Hi :) Good thinking, but looks it just loads things into memory a bit differently. I did a pointer search and found that the 0x320100 pointer works for me. So you can update all the pointers like this and give it a try. 

```
// Memory of JP m64py version
state("m64py", "JP") {
    uint gameRunTime : "mupen64plus.dll", 0x320100, 0x32C640;
    // ...
```

If it works for you then I can update the file (or you can make a pull request if you want)

Thank you :)

**Comment by andysandford** [comment]
I released this now, along with support for rosalies mupen :)

**Comment by arty-hlr** [comment]
Hi Andy, sorry for the very late response, I didn't see this! Thank you so much, looks great! :)
